### ISSUE TITLE
SearchApi seems to generate a wrong endpoint

### ISSUE THREAD

**Issue by akordecki** [manticoresoftware/manticoresearch-python#3] opened 2021-06-18 17:04 UTC
Hi,  
I want to try the Python API, but I couldn't send a SearchRequest to localhost.  
On every request, I'm getting:   
Exception when calling SearchApi->search: (501)  
Reason: Not Implemented  
HTTP response headers: HTTPHeaderDict({'Server': '3.6.0 96d61d8@210504 release', 'Content-Type': 'application/json; charset=UTF-8', 'Content-Length': '48'})  
HTTP response body: {"error":"//json/search - unsupported endpoint"}  
  
It looks like the client is adding an unnecessary "/" in front of the endpoint.    
  
Thanks,  
Alex

**Comment by sanikolaev** [comment] 2021-06-21 06:16
Hi @akordecki 

I can't reproduce it:
```
root@496b330a90a5:/# cat test.py
from __future__ import print_function
from pprint import pprint
import manticoresearch

config = manticoresearch.Configuration(
            host = "http://127.0.0.1:9308"
            )
client =  manticoresearch.ApiClient(config)
indexApi = manticoresearch.IndexApi(client)
searchApi = manticoresearch.SearchApi(client)
utilsApi = manticoresearch.UtilsApi(client)
r = searchApi.search({"index":"t","query":{"query_string":"@f abc"},"highlight":{"fields":["f"]}})
pprint(r)

root@496b330a90a5:/# python test.py
{'aggregations': None,
 'hits': {'hits': [{u'_id': u'6774547762756190209',
                    u'_score': 1500,
                    u'_source': {u'f': u'abc'},
                    u'highlight': {u'f': [u'<b>abc</b>']}}],
          'max_score': None,
          'total': 1},
 'profile': None,
 'timed_out': False,
 'took': 0}

root@496b330a90a5:/# cat /etc/*release*
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
...

root@496b330a90a5:/# python --version
Python 2.7.13

```

Please provide more details helping to reproduce the issue.

**Comment by akordecki** [comment] 2021-06-21 10:55
Thanks @sanikolaev, your script works for me also.
I found the problem.

**Comment by sanikolaev** [comment] 2021-06-24 10:10
> In the example in the documentation, the ApiClient is initialized without the configuration.

Right, thanks for pointing that out. We'll fix it.

**Comment by sanikolaev** [comment] 2021-07-09 06:28
Fixed in https://github.com/manticoresoftware/manticoresearch-python/commit/9c340ac6fc2d351f86e104071a65c8ea7c62cc20. Closing the issue

**Closed by sanikolaev** 2021-07-09 06:28 UTC
