### ISSUE TITLE
利用SQL进行multi-query

### ISSUE THREAD

**Issue by lljqy** [manticoresoftware/manticoresearch-python#4] opened 2021-11-11 15:31 UTC
利用SQL进行multi-query，怎么获取批量查询的结果？

**Comment by sanikolaev** [comment] 2021-11-12 10:39
Sorry I'm not sure I can translate your question properly. Could you please ask in English and best if you provide some examples: 
* code examples
* or smth which works via just SQL, but doesn't work out when you try to do the same via the python client

**Comment by lljqy** [comment] 2021-11-14 15:45
> Sorry I'm not sure I can translate your question properly. Could you please ask in English and best if you provide some examples:
> 
> * code examples
> * or smth which works via just SQL, but doesn't work out when you try to do the same via the python client

   I need to execute the following "first_sql" and "second_sql" statements at the same time, but the result of the execution can only get the query result of "first_sql"
![image](https://user-images.githubusercontent.com/26006550/141687861-a353aa87-2e14-41f1-bf99-35eed771a878.png)

**Comment by sanikolaev** [comment] 2021-11-15 04:33
This is a known issue. The root cause is the HTTP JSON protocol didn't allow multiple queries. That is already fixed in the latest Manticore Search dev version. Please give it a try. You can find dev packages on https://repo.manticoresearch.com/ or use dev apt/yum repors:
* ubuntu/debian - https://manual.manticoresearch.com/Installation/Debian_and_Ubuntu#Development-packages
* centos/rhel - https://manual.manticoresearch.com/Installation/RHEL_and_Centos#Development-packages

**Comment by sanikolaev** [comment] 2021-11-15 05:55
> That is already fixed in the latest Manticore Search dev version

Forget it. There was a bug.

**Comment by lljqy** [comment] 2021-11-20 03:18
> > That is already fixed in the latest Manticore Search dev version
> 
> Forget it. There was a bug.
I want to use it in a production environment. Is there a better recommended tools to use manticore for multi-queries in a python environment?

**Comment by sanikolaev** [comment] 2021-11-20 03:47
> Is there a better recommended tools to use manticore for multi-queries in a python environment?

Just use python mysql connector instead of the python client.

**Comment by lljqy** [comment] 2021-11-20 04:05
> 

You are talking about `pymysql` (https://pypi.org/project/PyMySQL/)?
I have used this toolkit, and found that the execution of `first_sql` and `second_sql` at the same time, and finally only the execution result of `first_sql`；And there is another problem. When the amount of data returned by my query is greater than 500,000, an error is reported directly: "Lost Connections"

**Comment by sanikolaev** [comment] 2021-11-20 05:31
This works fine for me:

```
snikolaev@dev:~$ cat manticore.py
import datetime
import mysql.connector

cnx = mysql.connector.connect(host='127.0.0.1', port='9306')
cursor = cnx.cursor()

cursor.execute("drop table if exists t")
cursor.execute("create table t(f text, a int)")
cursor.execute("insert into t values(0,'abc',123),(0,'def',123)")
results = cursor.execute("select * from t; select * from t where a=123", multi=True)

for cur in results:
    print('cursor:', cur)
    if cur.with_rows:
        print('result:', cur.fetchall())


cursor.close()
cnx.close()

snikolaev@dev:~$ python3 manticore.py
cursor: MySQLCursor: select * from t
result: [(2811600365064028171, 123, 'abc'), (2811600365064028172, 123, 'def')]
cursor: MySQLCursor: select * from t where a=123
result: [(2811600365064028171, 123, 'abc'), (2811600365064028172, 123, 'def')]
```

Try increasing https://mnt.cr/max_packet_size to avoid "lost connections".

**Comment by lljqy** [comment] 2021-11-20 15:42
> mysql.connector.connect(host='127.0.0.1', port='9306')

Thank you for your help, I solved the problem！

**Closed** 2021-11-22 02:51 UTC

**Comment by l1t1** [comment] 2023-07-19 06:14
> This works fine for me:
> 
> ```
> snikolaev@dev:~$ cat manticore.py
> import datetime
> import mysql.connector
> 
> cnx = mysql.connector.connect(host='127.0.0.1', port='9306')
> cursor = cnx.cursor()
> 
> cursor.execute("drop table if exists t")
> cursor.execute("create table t(f text, a int)")
> cursor.execute("insert into t values(0,'abc',123),(0,'def',123)")
> results = cursor.execute("select * from t; select * from t where a=123", multi=True)
> 
> for cur in results:
>     print('cursor:', cur)
>     if cur.with_rows:
>         print('result:', cur.fetchall())
> 
> 
> cursor.close()
> cnx.close()
> 
> snikolaev@dev:~$ python3 manticore.py
> cursor: MySQLCursor: select * from t
> result: [(2811600365064028171, 123, 'abc'), (2811600365064028172, 123, 'def')]
> cursor: MySQLCursor: select * from t where a=123
> result: [(2811600365064028171, 123, 'abc'), (2811600365064028172, 123, 'def')]
> ```
> 
> Try increasing https://mnt.cr/max_packet_size to avoid "lost connections".

I got following error, 
```
D:\Manticore>python \ms.py
cursor: MySQLCursor: select * from t
result: [(7352107006129340420, 123, 'abc'), (7352107006129340421, 123, 'def')]
cursor: MySQLCursor: select * from t where a=123
result: [(7352107006129340420, 123, 'abc'), (7352107006129340421, 123, 'def')]
Traceback (most recent call last):
  File "D:\Python38\lib\site-packages\mysql\connector\cursor.py", line 486, in _execute_iter
    result = next(query_iter)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "\ms.py", line 12, in <module>
    for cur in results:
RuntimeError: generator raised StopIteration
```
